spring.application.name=dux-integration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ============================================================
# SERVER
# ============================================================
server.port=9090

# ============================================================
# MY KEYCLOAK (Protects THIS app's endpoints)
# Realm  : DuxWeb  (DUX Keycloak)
# Callers must send: Authorization: Bearer <token from DuxWeb realm>
# ============================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ADMIN_URL:https://duxweb.pre-produx.asmtechtn.com/auth/}realms/${KEYCLOAK_ADMIN_REALM:DuxWeb}

# ============================================================
# DUX ERP - KEYCLOAK (To call DUX API)
# Realm  : DuxWeb
# Client : asm-apis
# ============================================================
dux.token-url=${KEYCLOAK_ADMIN_URL:https://duxweb.pre-produx.asmtechtn.com/auth/}realms/${KEYCLOAK_ADMIN_REALM:DuxWeb}/protocol/openid-connect/token
dux.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:asm-apis}
dux.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:WIIWVngUsQgSTyXB50AXm1YyeVtaog7V}

# ============================================================
# DUX ERP - API ENDPOINTS
# ============================================================
dux.user-url=${DUX_USER_URL:https://duxweb.pre-produx.asmtechtn.com/api/Activite/Userbylogin}
dux.station-url=${DUX_STATION_URL:https://duxweb.pre-produx.asmtechtn.com/api/Station/viewStation/}
dux.document-url=${DUX_DOCUMENT_URL:https://duxweb.pre-produx.asmtechtn.com/api/Document/getDocument/}
dux.details-doc-url=${DUX_DETAILS_DOC_URL:https://duxweb.pre-produx.asmtechtn.com/api/DetailsDoc2/}
dux.edit-ligne-url=${DUX_EDIT_LIGNE_URL:https://duxweb.pre-produx.asmtechtn.com/api/Document/editLigne}
dux.num-serie-url=${DUX_NUM_SERIE_URL:https://duxweb.pre-produx.asmtechtn.com/api/numSerie/getByNumBonSort/}
dux.delete-num-serie-url=${DUX_DELETE_NUM_SERIE_URL:https://duxweb.pre-produx.asmtechtn.com/api/numSerie/delete/}

