server:
  port: 9090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ADMIN_URL:https://duxweb.pre-produx.asmtechtn.com/auth/}realms/${KEYCLOAK_ADMIN_REALM:DuxWeb}
  datasource:
    timetree:
      url: jdbc:sqlserver://${TIMETREE_DB_HOST:sqlsrv}:1433;databaseName=ASM_TIMETREE;encrypt=false;trustServerCertificate=true;
      username: ${TIMETREE_DB_USER:sa}
      password: ${TIMETREE_DB_PASS:P5v9yast34Iy9qU}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    timetree:
      change-log: classpath:/db/changelog/timetree/master.xml
      default-schema: dbo

dux:
  token-url: ${KEYCLOAK_ADMIN_URL:https://duxweb.pre-produx.asmtechtn.com/auth/}realms/${KEYCLOAK_ADMIN_REALM:DuxWeb}/protocol/openid-connect/token
  user-url: ${DUX_USER_URL:https://duxweb.pre-produx.asmtechtn.com/api/Activite/Userbylogin}
  station-url: ${DUX_STATION_URL:https://duxweb.pre-produx.asmtechtn.com/api/Station/viewStation/}
  document-url: ${DUX_DOCUMENT_URL:https://duxweb.pre-produx.asmtechtn.com/api/Document/getDocument/}
  details-doc-url: ${DUX_DETAILS_DOC_URL:https://duxweb.pre-produx.asmtechtn.com/api/DetailsDoc2/}
  client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:asm-apis}
  client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:WIIWVngUsQgSTyXB50AXm1YyeVtaog7V}